### PR TITLE
working example gromit, energy and decomposition

### PR DESCRIPTION
**Pull request by felipeZ**
New example with 3 steps: `gromit`, `energies` and `decomposition`

### CODE REVIEW

**Comment by LourensVeen** [comment]
It's working! Nice! A few questions/comments though:
- What happened to the secondaryFiles? It looks like itp is a separate argument now again?
- The input files now have generic names, but the output file is named after the CYP we're processing. Could that be consistent?

**Comment by felipeZ** [comment]
Most of the *itp* files are secondary files: 
 `attype.itp  compound_ref-posre.itp  ref_conf_1-posre.itp`

Only the `compound_ref.itp` file is a positional argument.
And you are right about the naming space, I'll fix it.

**Comment by LourensVeen** [comment]
But the script is using add_input_file, not add_secondary_file?

**Comment by felipeZ** [comment]
OOPS!!!
I'll fix it

**Pull request merged**
